server:
  port: 18088
spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.137.128
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false #\u5173\u95EDthymeleaf\u7684\u7F13\u5B58\u529F\u80FD \u5F00\u53D1\u65F6
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
pool:
  coreSize: 50
  maxSize: 100
  timeOut: 60
  blockQueueSize: 200

