server:
  port: 18081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: 192.168.137.128
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.128:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: "123456Abc@"
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath*:mapper/pms/**/*.xml
  global-config:
    db-config:
      id-type: assign_id
  type-aliases-package: com.atguigu.gmall.pms

